# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: "cleanup-concat-service"
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: "abs"
    spotify.com/description: |
      Shift to remove unused Concat service.
spec:
  shiftIdentityOptOut: true
  containers:
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 1042:3042 /workdir && ls -la /workdir"]
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:20250515110226-9f04921f
      args:
        [
          "--model=o3-mini",
          "--no-goose-in-docker",
          "--agent=duck",
          "--format",
          "--verify-command=mvn verify -q",
          "--verify-pattern=BUILD SUCCESS",
          "run",
          "--examples", "gs://honk-plans/instructions/remove-concat-service/examples",
          "--git-grep=git grep -l --all-match 'Concat*'",
          "gs://honk-plans/instructions/remove-concat-service/instructions.md",
        ]
      nonRootUser: true
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: "ai-migration: cleanup-concat-service"
    description: |
      Shift to remove unused Concat service.

      🪿 This PR has been created by honk based on the [cleanup-concat-service plan](https://ghe.spotify.net/genai-migration/ai-migrations/tree/master/instructions/cleanup-concat-service)
    commitMessage: "cleanup-concat-service: honk!"

  rollout:
    createCodeChanges: true
    createPullRequests: false # enable when ready to rollout to customers

  targetRepositorySource:
    codesearch:
      query: 'addService\(ConcatService lifecycle:"production" lang:"Java" -repo:"spotify/services-pilot"'
