# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: "hog-cleanup-honk-version"
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: "abs"
    spotify.com/description: |
      This is a Fleetshift using Honk to remove config variables regarding HoG in services configuration files
spec:
  # We run under the standard fleetshift service account. This simplifies permission managment.
  shiftIdentityOptOut: true
  containers:

    # Honk does not run as root. First we own the workdir to make sure we can write to it.
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 1042:3042 /workdir && ls -la /workdir"]

    # This is where honk runs. Configure Honk in args.
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args:
        [
          "run",
          "gs://honk-plans/instructions/hog-cleanup-honk-version/instructions.md",
        ]
      nonRootUser: true

    # Move ownership of the workdir back to root. git needs this.
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: "ai-migration: hog-cleanup-honk-version"
    description: |
      This is a Fleetshift using Honk to remove config variables regarding HoG in services configuration files 

      🪿 This PR has been created by honk based on the [hog-cleanup-honk-version plan](https://ghe.spotify.net/genai-migration/ai-migrations/tree/master/instructions/hog-cleanup-honk-version)
    commitMessage: "hog-cleanup-honk-version: honk!"

  rollout:
    createCodeChanges: true
    createPullRequests: false # enable when ready to rollout to customers

  targetRepositorySource:
    codesearch:
      query: 'f:\.conf$ hog -repo:"abs/cleanup-config-fleetshift" -repo:"abs/cleanup-hog-config-fleetshift" -repo:"spotify/services-pilot" -repo:"fabric/grpc-cross-zone-fleetshift"  -repo:"fabric/remove-hog-completly-shift"'
