# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: replace-base64-guava
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: marcbr
    spotify.com/description: Replace usage of Guava Base64 encoding
spec:
  shiftIdentityOptOut: true
  containers:
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ['sh', '-c', "chown -R 1042:3042 /workdir && ls -la /workdir"]
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args: ["--model=o3-mini", "--no-goose-in-docker", "run", "--examples", "gs://honk-plans/instructions/replace-base64-guava/examples", "gs://honk-plans/instructions/replace-base64-guava/instructions.md"]
      nonRootUser: true
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ['sh', '-c', "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: "ai-migration: Replace Guava Base64 encoder/decoder"
    description: |
      Migrating from Guava's BaseEncoding.base64() to the JDK equivalent.

      🪿 This PR has been created by honk based on the [replace-base64-guava plan](https://ghe.spotify.net/genai-migration/ai-migrations/tree/master/instructions/replace-base64-guava)
    commitMessage: "ai-migration: Replace Guava Base64 encoder/decoder"

  rollout:
    createCodeChanges: true
    createPullRequests: true

  targets:
    where:
      allMatch:
        - component:
            lifecycle: experimental
        - subpath:
            at: "**/*.java"
            withContentsMatching: "BaseEncoding.base64()"
    unless:
      inList:
        - repository: spotify/services-pilot
        - repository: genai-migration/ai-migrations
