# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: replace-guava-base64
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: marcbr
    spotify.com/description: Replace usage of Guava Base64 encoding
spec:
  shiftIdentityOptOut: true
  containers:
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2024.12-1@sha256:d49f79f72b49a99e96eb6426a278eaff3a26657d3ed434f4a04ff00a3f7315e3
      command: ['sh', '-c', "chown -R 1042:3042 /workdir && ls -la /workdir"]
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args: ["--model=o3-mini", "--no-goose-in-docker", "run", "--examples", "gs://honk-plans/instructions/replace-guava-base64/examples", "gs://honk-plans/instructions/replace-guava-base64/instructions.md"]
      nonRootUser: true
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2024.12-1@sha256:d49f79f72b49a99e96eb6426a278eaff3a26657d3ed434f4a04ff00a3f7315e3
      command: ['sh', '-c', "rm /workdir/plan.md && chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: "ai-migration: Replace Guava Base64 encoder/decoder"
    description: |
      Migrating from Guava's BaseEncoding.base64() to the JDK equivalent.

      🪿 This PR has been created by honk based on the [replace-guava-base64 plan](https://ghe.spotify.net/genai-migration/ai-migrations/tree/master/instructions/replace-guava-base64)
    commitMessage: "ai-migration: Replace Guava Base64 encoder/decoder"

  rollout:
    createCodeChanges: true
    createPullRequests: false

  targets:
    where:
      allMatch:
        - component:
            lifecycle: experimental
        - subPath:
            at: "*.java"
            withContentsMatching: "BaseEncoding.base64()"
