# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: "runtime-yaml-update"
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: "warpspeed"
    spotify.com/description: |
      This shift updates the runtime yaml in service repos, in accordance with the runtime crd changes. Currently it will remove the `roles` key and the `resourceQuota` key (if the resourceQuota falls within the defaults). 
spec:
  shiftIdentityOptOut: true
  containers:
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 1042:3042 /workdir && ls -la /workdir"]
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args:
        [
          "--no-goose-in-docker",
          "run",
          "gs://honk-plans/instructions/runtime-yaml-update/instructions.md",
        ]
      nonRootUser: true
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2025.2-2@sha256:5c83c28da296869982387e342cae2b105fe6d33f66b3be55c7cb7313969aed79
      command: ["sh", "-c", "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: "ai-migration: runtime-yaml-update"
    description: |
      This shift updates the runtime yaml in service repos, in accordance with the runtime crd changes. Currently it will remove the `roles` key and the `resourceQuota` key (if the resourceQuota falls within the defaults). 

      🪿 This PR has been created by honk based on the [runtime-yaml-update plan](https://ghe.spotify.net/genai-migration/ai-migrations/tree/master/instructions/runtime-yaml-update)
    commitMessage: "runtime-yaml-update: honk!"

  rollout:
    createCodeChanges: true
    createPullRequests: false # enable when ready to rollout to customers

  # For how to write target queries, see:
  # https://backstage.spotify.net/docs/default/system/fleetshift-system/targeting-repositories/directory-level-targeting/
  targetRepositorySource:
    codesearch:
      query: |
        roles file:runtime.yaml owner:"warpspeed"
