# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: update-component-types
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: ssa
    spotify.com/description: Update of the component type. Update made by the AI agent Honk.
spec:
  shiftIdentityOptOut: true
  containers:
      # Honk does not run as root. First we own the workdir to make sure we can write to it.
    - name: chown-non-root
      image: cgr.dev/chainguard/bash:latest # Chainguard is vetted by security. They provide images with CVE scanning.
      command: ['sh', '-c', "chown -R 1042:3042 /workdir && ls -la /workdir"]
      # This is where honk runs.
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args: ["--model=o3-mini", "--no-goose-in-docker", "run", "gs://honk-plans/instructions/update-component-type/instructions.md"]
      nonRootUser: true
      # Move ownership of the workdir back to root. git needs this.
    - name: chown-root
      image: cgr.dev/chainguard/bash:latest # Chainguard is vetted by security. They provide minimal images with CVE scanning.
      command: ['sh', '-c', "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: Update component type
    description: |
      Update of the component type. Update made by the AI agent Honk.
    commitMessage: Update component type.

  rollout:
    createCodeChanges: true
    createPullRequests: false

  targets:
    where:
      allMatch:
        - subpath:
            at: "**/service-info.yaml"
        - component:
            type: service
