# See manifest documentation for details:
# https://backstage.spotify.net/docs/default/system/fleetshift-system/shift-manifest/shift-manifest-reference-guide/#shift-manifest-reference-guide
apiVersion: fleetshift.spotify.com/v1
kind: Shift
metadata:
  name: update-component-types
  namespace: genai-migration-experiment
  annotations:
    spotify.com/owner: ssa
    spotify.com/description: Central location of AI powered fleet shifts for migrations and other fleet wide changes.
spec:
  shiftIdentityOptOut: true
  containers:
    - name: chown-non-root
      image: gcr.io/spotify-base-images/noble:2024.12-1@sha256:d49f79f72b49a99e96eb6426a278eaff3a26657d3ed434f4a04ff00a3f7315e3
      command: ['sh', '-c', "chown -R 1042:3042 /workdir && ls -la /workdir"]
    - name: honk
      image: gcr.io/genai-migration-experiment/gaggle:latest
      args: ["--model=o3-mini", "--no-goose-in-docker", "run", "gs://honk-plans/instructions/update-component-type/instructions.md"]
      nonRootUser: true
    - name: chown-root
      image: gcr.io/spotify-base-images/noble:2024.12-1@sha256:d49f79f72b49a99e96eb6426a278eaff3a26657d3ed434f4a04ff00a3f7315e3
      command: ['sh', '-c', "chown -R 0:0 /workdir && ls -la /workdir"]

  pullRequest:
    title: Update component type
    description: |
      Update of the component type. Update made by the AI agent Honk.
    commitMessage: Update component type.

  rollout:
    createCodeChanges: true
    createPullRequests: false

  targetRepositorySource:
      codesearch:
          query: 'ct:"service" lifecycle:"experimental" lang:"YAML" file:"service-info.yaml" -repo:"spotify/services-pilot" owner:"fabric"'
