serviceauth {
  enabled: true
  enforcing: false
  defaultAction: "deny"
  accessPolicies: [
    { matchType: "exact", path: "/v0/ping", method: "GET", principals: ["*"] },
    { matchType: "exact", path: "/concat", method: "POST", principals: ["*"] },
    { matchType: "exact", path: "/grpc.health.v1.Health/Check", principals: ["*"] },
    { matchType: "exact", path: "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo", principals: ["*"] },
    { matchType: "prefix", path: "/spotify.meta.v1.MetaService/", principals: ["*"] },
    { matchType: "prefix", path: "/spotify.concat.v1.ConcatService/", principals: ["*"] },
  ]
}