load("@spotify//tools/jvm:android.bzl", "android_local_test_suite")
load("@spotify//tools/jvm:kt.bzl", "kt_jvm_library", "kt_jvm_test_suite")

kt_jvm_library(
    name = "helpers",
    testonly = True,
    srcs = [
        "fakes/FakeConnectVolumeInteractor.kt",
        "fakes/FakeLocalVolumeInteractor.kt",
        "fakes/FakeMediaRouterSelectedObserver.kt",
        "fakes/FakePlaybackVolumeProvider.kt",
        "fakes/FakeRemoteVolumeWidgetPlugin.kt",
        "fakes/FakeSystemContentObserver.kt",
        "fakes/FakeSystemVolumeObserver.kt",
        "fakes/FakeVolumeEndpoint.kt",
        "fakes/FakeVolumeInjector.kt",
        "fakes/FakeVolumeInterceptor.kt",
        "fakes/FakeVolumeStateProvider.kt",
        "spikedetector/ConnectAggregatorEntityTestHelper.kt",
        "spikedetector/FakeVolumeUpdateListener.kt",
    ],
    associates = ["//src/main/java/com/spotify/connect/volumeimpl:volumeimpl_kt"],
    prune_transitive_deps = False,
    deps = [
        "//src/main/java/com/spotify/connect/connectaggregatortest",
        "//src/main/java/com/spotify/connect/volumeimpl",
        "@maven//:androidx_test_core",
        "@maven//:com_google_truth_truth",
        "@maven//:io_reactivex_rxjava3_rxjava",
        "@maven//:junit_junit",
        "@maven//:org_junit_vintage_junit_vintage_engine",
        "@maven//:org_robolectric_shadows_framework",
    ],
)

android_local_test_suite(
    name = "tests",
    size = "medium",
    srcs = [
        "DefaultConnectVolumeInteractorTest.kt",
        "DefaultPlaybackVolumeProviderTest.kt",
        "buffers/VolumeBufferingInterceptorTest.kt",
        "controllers/DebounceSystemVolumeObserverTest.kt",
        "controllersmobius/LocalVolumeControllerMobiusTest.kt",
        "controllersmobius/MasterVolumeControllerMobiusTest.kt",
        "keys/DefaultConnectOnKeyDownDelegateTest.kt",
        "mobius/domain/VolumeLogicTest.kt",
        "mobius/effecthandlers/VolumeEffectHandlersKtTest.kt",
        "mobius/eventsources/VolumeEventSourcesKtTest.kt",
        "spikedetector/MobiusAppVolumeStateTest.kt",
        "spikedetector/VolumeSpikeDetectorTest.kt",
        "widget/DefaultVolumeWidgetViewModelTest.kt",
    ],
    associates = [
        ":helpers",
        "//src/main/java/com/spotify/connect/volumeimpl:volumeimpl_kt",
    ],
    deps = [
        "//src/main/java/com/spotify/accessory/statemanagertest",
        "//src/main/java/com/spotify/connect/connectaggregatortest",
        "//src/main/java/com/spotify/connect/coretest",
        "//src/main/java/com/spotify/connect/flagstest",
        "//src/main/java/com/spotify/connect/helperstest",
        "//src/main/java/com/spotify/connect/instrumentationtest",
        "//src/main/java/com/spotify/connect/mediaroutertest",
        "//src/main/java/com/spotify/connect/volumeimpl",
        "//src/main/java/com/spotify/connect/volumetest",
        "//src/main/java/com/spotify/connect/wrapperstest",
        "//src/main/java/com/spotify/jam/jamtest",
        "//src/main/java/com/spotify/legacyglue/themeglue",
        "@maven//:androidx_test_core",
        "@maven//:androidx_test_core_ktx",
        "@maven//:com_google_truth_truth",
        "@maven//:com_spotify_mobius_mobius_test",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_test",
        "@maven//:org_junit_vintage_junit_vintage_engine",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_robolectric_robolectric",
        "@maven//:org_robolectric_shadows_framework",
        "@spotify//src/main/java/com/spotify/time:fake_clock",
        "@spotify//src/test/java/com/spotify/support/android",
        "@spotify//src/test/java/com/spotify/support/dagger",
        "@spotify//third_party/core:com_spotify_clientcore_connect_volume_java_testutil",
        "@spotify//third_party/core:com_spotify_clientcore_src_main_java_com_spotify_audio_playbackesperanto",
        "@spotify//third_party/core:com_spotify_clientcore_src_main_java_com_spotify_cosmos_cosmos",
        "@spotify//third_party/core:com_spotify_clientcore_src_main_java_com_spotify_esperanto_esperanto",
        "@spotify//third_party/core:com_spotify_clientcore_src_main_java_com_spotify_esperanto_esperantoimpl",
    ],
)

kt_jvm_test_suite(
    name = "jvm_tests",
    size = "small",
    srcs = [
        "ExtensionsKtTest.kt",
        "endpoints/VolumeEndpointResolverTest.kt",
        "mobius/VolumePluginTest.kt",
        "widget/NowPlayingQueueVolumeWidgetPluginTest.kt",
    ],
    associates = [
        ":helpers",
        "//src/main/java/com/spotify/connect/volumeimpl:volumeimpl_kt",
    ],
    deps = [
        "//src/main/java/com/spotify/connect/connectaggregatortest",
        "//src/main/java/com/spotify/connect/coretest",
        "//src/main/java/com/spotify/connect/providertest",
        "//src/main/java/com/spotify/connect/volumeimpl",
        "//src/main/java/com/spotify/connect/volumetest",
        "@maven//:androidx_test_core",
        "@maven//:com_google_truth_truth",
        "@maven//:com_spotify_mobius_mobius_test",
        "@maven//:junit_junit",
        "@maven//:org_junit_vintage_junit_vintage_engine",
        "@maven//:org_robolectric_shadows_framework",
        "@spotify//src/main/java/com/spotify/time:fake_clock",
        "@spotify//third_party/core:com_spotify_clientcore_connect_volume_java_testutil",
    ],
)
