apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: ai-migrations-iam-fleetshift-ar-viewer-role
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: projects/genai-migration-experiment
    kind: Project
  bindings:
  - role: roles/artifactregistry.reader
    members:
    - member:
        serviceAccount:tycoon-job-account@fleetshift.iam.gserviceaccount.com
