apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-honk-plans-viewer
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/genai-migration-experiment"
  bindings:
  - role: roles/storage.objectViewer
    condition:
      expression: 'resource.name.startsWith("projects/_/buckets/honk-plans")'
      title: "Read permissions on honk-plans bucket"
      description: "Read permissions on honk-plans bucket for Fleetshift SA"
    members:
    - member:
        serviceAccount:tycoon-job-account@fleetshift.iam.gserviceaccount.com
