apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: ai-migrations-iam-google-secret-accessor
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: "projects/genai-migration-experiment/secrets/google"
  bindings:
  - role: roles/secretmanager.secretAccessor
    members:
    - member: 
        serviceAccount:tycoon-job-account@fleetshift.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: ai-migrations-iam-openai-secret-accessor
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: "projects/genai-migration-experiment/secrets/openai"
  bindings:
  - role: roles/secretmanager.secretAccessor
    members:
    - member: 
        serviceAccount:tycoon-job-account@fleetshift.iam.gserviceaccount.com