apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-gcr-viewer
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/genai-migration-experiment"
  bindings:
  - role: roles/storage.objectViewer
    condition:
      expression: 'resource.name.startsWith("projects/_/buckets/artifacts.genai-migration-experiment.appspot.com")
        || resource.name.startsWith("projects/_/buckets/asia.artifacts.genai-migration-experiment.appspot.com")
        || resource.name.startsWith("projects/_/buckets/eu.artifacts.genai-migration-experiment.appspot.com")
        || resource.name.startsWith("projects/_/buckets/us.artifacts.genai-migration-experiment.appspot.com")'
      title: "Only on GCR"
      description: "GCR read access for everything in genai-migration-experiment to Fleetshift SA"
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-honk-plans-viewer
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/genai-migration-experiment"
  bindings:
  - role: roles/storage.objectViewer
    condition:
      expression: 'resource.name.startsWith("projects/_/buckets/honk-plans")'
      title: "Read permissions on honk-plans bucket"
      description: "Read permissions on honk-plans bucket for Fleetshift SA"
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-honk-telemetry-writer
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/genai-migration-experiment"
  bindings:
  - role: roles/storage.objectCreator
    condition:
      expression: 'resource.name.startsWith("projects/_/buckets/honk-telemetry")'
      title: "Write permissions on honk-telemetry bucket"
      description: "Write permissions on honk-telemetry bucket for Fleetshift SA"
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-secret-accessor
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: "projects/genai-migration-experiment/secrets/google"
  bindings:
  - role: roles/secretmanager.secretAccessor
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-secret-accessor
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
    external: "projects/genai-migration-experiment/secrets/openai"
  bindings:
  - role: roles/secretmanager.secretAccessor
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-service-usage-viewer
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/genai-migration-experiment"
  bindings:
  - role: roles/serviceusage.serviceUsageViewer
    condition:
      expression: 'resource.name.startsWith("projects/")'
      title: "View service usage"
      description: "View service usage information for Fleetshift SA"
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: shift-update-metadata-shift-fleetshift-ar-viewer-role
  namespace: genai-migration-experiment
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: projects/genai-migration-experiment
    kind: Project
  bindings:
  - role: roles/artifactregistry.reader
    members:
    - member: 
        serviceAccount:shift-update-metadata-shift@genai-migration-experiment.iam.gserviceaccount.com
